version: "2"

services:
  app:
    restart: always
    build: ./frontend
    container_name: node-app
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    # environment:
    #   - NODE_ENV=development
